### ISSUE TITLE
TWRP 3.7.0-9.0 for Galaxy Note 5

### ISSUE THREAD

**Issue by TanByv** [fakemanoan/TWRP-Releases#2]
TWRP 3.7.0-9.0 is stated as a requirement to install LineageOS 19.1 on Galaxy Note 5 but I couldn't locate any binaries for it in neither your website nor here in this repo. Can you shed some light on that please?

**Comment by fakemanoan** [comment]
working on my own twrp releases
in the mean time you can use these: https://drive.google.com/drive/folders/1gAlPsZIkYM-XYWu-JWJCDgwJ-60h0Ss2
